#!/usr/bin/bash
set -o errexit
set -o noclobber

if [[ -d .venv ]]; then
    venv_path=".venv"
elif [[ -d venv ]]; then
    venv_path="venv"
else
    echo "No venv exists named \"venv\" or \".venv\". Make one first."
    exit 1
fi

echo "Using venv path \"${venv_path}\" and python version $(python -v); entering venv"
source ${venv_path}/bin/activate || source ${venv_path}/Scripts/activate

python -m pinguu